name: Continuos Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Inicia Ambiente
      # Aqui subimos TUDO (App e Postgres) e esperamos um pouco
      run: |
        docker compose up -d
        sleep 15

    - name: Lint
      run: |
        echo "üîç Iniciando a verifica√ß√£o de estilo..."
        docker run --rm -v .:/app -w /app golangci/golangci-lint golangci-lint run controllers/ database/ models/ routes/ || (echo "‚ùå ERRO: Seu c√≥digo est√° bagun√ßado!" && exit 1)
        echo "‚úÖ SUCESSO: C√≥digo limpo!"

    - name: Test
      run: |
        # O comando abaixo agora vai funcionar porque o 'app' estar√° rodando
        docker compose exec -T app go test ./... || (echo "‚ùå ERRO: O teste falhou!" && exit 1)
        echo "‚úÖ SUCESSO: Deu tudo certo!"

    - name: Build
      run: go build main.go

    - name: Projeto compilado
      uses: actions/upload-artifact@v4
      with:
        name: projeto_compilado
        path: main